// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Chintu Pandey",
    email: "chintu@pandey.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Data Structures", "Algorithms"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Pappu Yadav",
    email: "pappu@yadav.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Operating Systems", "Computer Networks"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Bablu Tiwari",
    email: "bablu@tiwari.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Database Management Systems"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Munna Bhai",
    email: "munna@bhai.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Artificial Intelligence"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Golu Sharma",
    email: "golu@sharma.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Machine Learning", "Cyber Security"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Bunty Verma",
    email: "bunty@verma.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Software Engineering"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Chhotu Singh",
    email: "chhotu@singh.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Cloud Computing", "Big Data"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Tinku Jaiswal",
    email: "tinku@jaiswal.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Computer Architecture", "Embedded Systems"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Lalu Mishra",
    email: "lalu@mishra.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Cryptography", "Blockchain"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Pintu Gupta",
    email: "pintu@gupta.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Internet of Things"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Baburao ganpatrao apte",
    email: "john@doe.com",
    photo:
      "https://media.licdn.com/dms/image/v2/D4D03AQFBknH8BW6ZKA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1696866588023?e=2147483647&v=beta&t=YCQHHth3T97MeLNzaW9LyU6yzA69bwX5NblNGzJLJqY",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Circuit Singh",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Chhote pandit",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Pappu Pager",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Crime master Gogo",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Majnu Bhai",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Chatur ramalingam",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Award Anshuman",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Sachin Tichkule",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Munna Bhaiya",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "C++",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "Data Structures",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "DBMS",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "computer Networks",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Operating Systems",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "Java Programming",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Web Development",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Basics of statistics",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Design and Analysis of Algorithms",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Software Engineering",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Ravi Sharma",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Amit Mehta",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Sunil Rao",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Neha Iyer",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Vikram Desai",
  },
  {
    id: 6, // Fixed duplicate ID
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Pooja Nair",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Suresh Kulkarni",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Anjali Joshi",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Rohan Verma",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Meera Patel",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "Data Structures",
    class: "1A",
    teacher: "Rajesh Sharma",
  },
  {
    id: 2,
    subject: "Algorithms",
    class: "2A",
    teacher: "Priya Patel",
  },
  {
    id: 3,
    subject: "Operating Systems",
    class: "3A",
    teacher: "Amit Verma",
  },
  {
    id: 4,
    subject: "Computer Networks",
    class: "1B",
    teacher: "Sneha Iyer",
  },
  {
    id: 5,
    subject: "Database Management",
    class: "4A",
    teacher: "Vikram Desai",
  },
  {
    id: 6,
    subject: "Cybersecurity",
    class: "5A",
    teacher: "Meera Nair",
  },
  {
    id: 7,
    subject: "Artificial Intelligence",
    class: "6A",
    teacher: "Suresh Menon",
  },
  {
    id: 8,
    subject: "Machine Learning",
    class: "6B",
    teacher: "Anjali Rao",
  },
  {
    id: 9,
    subject: "Cloud Computing",
    class: "6C",
    teacher: "Rohan Kulkarni",
  },
  {
    id: 10,
    subject: "Software Engineering",
    class: "4B",
    teacher: "Deepika Joshi",
  },
];


export const examsData = [
  {
    id: 1,
    subject: "Data Structures",
    class: "1A",
    teacher: "Rajesh Sharma",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "Algorithms",
    class: "2A",
    teacher: "Priya Patel",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Operating Systems",
    class: "3A",
    teacher: "Amit Verma",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Computer Networks",
    class: "1B",
    teacher: "Sneha Iyer",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Database Management",
    class: "4A",
    teacher: "Vikram Desai",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Cybersecurity",
    class: "5A",
    teacher: "Meera Nair",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "Artificial Intelligence",
    class: "6A",
    teacher: "Suresh Menon",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Machine Learning",
    class: "6B",
    teacher: "Anjali Rao",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Cloud Computing",
    class: "7A",
    teacher: "Rohan Kulkarni",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Software Engineering",
    class: "8A",
    teacher: "Deepika Joshi",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Data Structures",
    class: "1A",
    teacher: "Rajesh Sharma",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "Algorithms",
    class: "2A",
    teacher: "Suresh Verma",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Operating Systems",
    class: "3A",
    teacher: "Priya Iyer",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Database Management Systems",
    class: "1B",
    teacher: "Anita Desai",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Computer Networks",
    class: "4A",
    teacher: "Vikram Joshi",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Software Engineering",
    class: "5A",
    teacher: "Meera Reddy",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "Artificial Intelligence",
    class: "6A",
    teacher: "Amitabh Kulkarni",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Machine Learning",
    class: "6B",
    teacher: "Neha Bansal",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Cyber Security",
    class: "7A",
    teacher: "Ravi Nair",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Cloud Computing",
    class: "8A",
    teacher: "Deepak Mehta",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Programming Fundamentals",
    class: "1A",
    teacher: "Rajesh Kumar",
    student: "Aarav Sharma",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "Data Structures",
    class: "2A",
    teacher: "Priya Singh",
    student: "Ananya Patel",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Algorithms",
    class: "3A",
    teacher: "Vikram Joshi",
    student: "Ishaan Gupta",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Database Management",
    class: "1B",
    teacher: "Neha Reddy",
    student: "Riya Mehta",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Operating Systems",
    class: "4A",
    teacher: "Arun Mishra",
    student: "Siddharth Rao",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Computer Networks",
    class: "5A",
    teacher: "Kavita Desai",
    student: "Vivaan Choudhury",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "Software Engineering",
    class: "6A",
    teacher: "Rahul Verma",
    student: "Aditi Nair",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Artificial Intelligence",
    class: "6B",
    teacher: "Anjali Kapoor",
    student: "Kabir Malhotra",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Machine Learning",
    class: "7A",
    teacher: "Sanjay Gupta",
    student: "Myra Singh",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Cybersecurity",
    class: "8A",
    teacher: "Deepak Sharma",
    student: "Rohan Iyer",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];
export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


export const calendarEvents = [
  {
    title: "Data Structures",
    allDay: false,
    start: new Date(2025, 1, 8, 8, 0),
    end: new Date(2025, 1, 8, 8, 45),
  },
  {
    title: "Algorithms",
    allDay: false,
    start: new Date(2025, 1, 8, 9, 0),
    end: new Date(2025, 1, 8, 9, 45),
  },
  {
    title: "Database Systems",
    allDay: false,
    start: new Date(2025, 1, 8, 10, 0),
    end: new Date(2025, 1, 8, 10, 45),
  },
  {
    title: "Operating Systems",
    allDay: false,
    start: new Date(2025, 1, 8, 11, 0),
    end: new Date(2025, 1, 8, 11, 45),
  },
  {
    title: "Computer Networks",
    allDay: false,
    start: new Date(2025, 1, 8, 13, 0),
    end: new Date(2025, 1, 8, 13, 45),
  },
  {
    title: "Software Engineering",
    allDay: false,
    start: new Date(2025, 1, 8, 14, 0),
    end: new Date(2025, 1, 8, 14, 45),
  },
  {
    title: "Algorithms",
    allDay: false,
    start: new Date(2025, 1, 9, 9, 0),
    end: new Date(2025, 1, 9, 9, 45),
  },
  {
    title: "Database Systems",
    allDay: false,
    start: new Date(2025, 1, 9, 10, 0),
    end: new Date(2025, 1, 9, 10, 45),
  },
  {
    title: "Operating Systems",
    allDay: false,
    start: new Date(2025, 1, 9, 11, 0),
    end: new Date(2025, 1, 9, 11, 45),
  },
  {
    title: "Software Engineering",
    allDay: false,
    start: new Date(2025, 1, 9, 14, 0),
    end: new Date(2025, 1, 9, 14, 45),
  },
  {
    title: "Data Structures",
    allDay: false,
    start: new Date(2025, 1, 10, 8, 0),
    end: new Date(2025, 1, 10, 8, 45),
  },
  {
    title: "Database Systems",
    allDay: false,
    start: new Date(2025, 1, 10, 10, 0),
    end: new Date(2025, 1, 10, 10, 45),
  },
  {
    title: "Computer Networks",
    allDay: false,
    start: new Date(2025, 1, 10, 13, 0),
    end: new Date(2025, 1, 10, 13, 45),
  },
  {
    title: "Software Engineering",
    allDay: false,
    start: new Date(2025, 1, 10, 14, 0),
    end: new Date(2025, 1, 10, 14, 45),
  },
  {
    title: "Algorithms",
    allDay: false,
    start: new Date(2025, 1, 11, 9, 0),
    end: new Date(2025, 1, 11, 9, 45),
  },
  {
    title: "Database Systems",
    allDay: false,
    start: new Date(2025, 1, 11, 10, 0),
    end: new Date(2025, 1, 11, 10, 45),
  },
  {
    title: "Operating Systems",
    allDay: false,
    start: new Date(2025, 1, 11, 11, 0),
    end: new Date(2025, 1, 11, 11, 45),
  },
  {
    title: "Software Engineering",
    allDay: false,
    start: new Date(2025, 1, 11, 14, 0),
    end: new Date(2025, 1, 11, 14, 45),
  },
  {
    title: "Data Structures",
    allDay: false,
    start: new Date(2025, 1, 12, 8, 0),
    end: new Date(2025, 1, 12, 8, 45),
  },
  {
    title: "Algorithms",
    allDay: false,
    start: new Date(2025, 1, 12, 9, 0),
    end: new Date(2025, 1, 12, 9, 45),
  },
  {
    title: "Operating Systems",
    allDay: false,
    start: new Date(2025, 1, 12, 11, 0),
    end: new Date(2025, 1, 12, 11, 45),
  },
  {
    title: "Computer Networks",
    allDay: false,
    start: new Date(2025, 1, 12, 13, 0),
    end: new Date(2025, 1, 12, 13, 45),
  },
  {
    title: "Software Engineering",
    allDay: false,
    start: new Date(2025, 1, 12, 14, 0),
    end: new Date(2025, 1, 12, 14, 45),
  },
];
